CREATE TABLE COMCODE (
	CREATED_DT				DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT				DATE		 	NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,  
	SYSTEM_TYPE_CODE		VARCHAR2(3)		NOT NULL 	,      
  	CODE_ID	  	      		VARCHAR2(255) 	NOT NULL 	,
  	CODE					VARCHAR2(255) 	NOT NULL 	,
	CODE_NAME				VARCHAR2(255) 	NOT NULL 	,
	CODE_NAME_ABBR			VARCHAR2(255) 	NULL 		,	
  	P_CODE_ID  		    	VARCHAR2(255)	NULL 		,
	FROM_DT					DATE			NOT NULL	,
	TO_DT					DATE			NOT NULL	,
	HIERARCHY_LEVEL			INT	DEFAULT(1)	NOT NULL	,
	PRT_SEQ					INT				NULL		,		
  	LOW_LEVEL_CODE_LENGTH	INT				NULL		,
	CMT					  	VARCHAR2(2000) 	NULL 		,
	constraint pk_comcode primary key(SYSTEM_TYPE_CODE, CODE_ID)	
); 

COMMENT ON TABLE COMCODE IS '공통코드정보';
COMMENT ON COLUMN COMCODE.CREATED_DT IS '최초등록일시';
COMMENT ON COLUMN COMCODE.CREATED_USER_ID IS '최초등록유저';
COMMENT ON COLUMN COMCODE.CREATED_HOST_IP IS '최초등록IP';
COMMENT ON COLUMN COMCODE.CREATED_APP_URL IS '최초등록APPURL';
COMMENT ON COLUMN COMCODE.MODIFIED_DT IS '최종수정일시';
COMMENT ON COLUMN COMCODE.MODIFIED_USER_ID IS '최종수정유저';
COMMENT ON COLUMN COMCODE.MODIFIED_HOST_IP IS '최종수정IP';
COMMENT ON COLUMN COMCODE.MODIFIED_APP_URL IS '최종수정APPURL';
COMMENT ON COLUMN COMCODE.SYSTEM_TYPE_CODE IS '시스템구분코드';
COMMENT ON COLUMN COMCODE.CODE_ID IS '코드ID';
COMMENT ON COLUMN COMCODE.CODE IS '공통코드';
COMMENT ON COLUMN COMCODE.CODE_NAME IS '코드명';
COMMENT ON COLUMN COMCODE.CODE_NAME_ABBR IS '코드명약어';
COMMENT ON COLUMN COMCODE.P_CODE_ID IS '상위코드ID';
COMMENT ON COLUMN COMCODE.FROM_DT IS '시작일시';
COMMENT ON COLUMN COMCODE.TO_DT IS '종료일시';
COMMENT ON COLUMN COMCODE.HIERARCHY_LEVEL IS '계층단계(1부터 시작)';
COMMENT ON COLUMN COMCODE.PRT_SEQ IS '출력순서';
COMMENT ON COLUMN COMCODE.LOW_LEVEL_CODE_LENGTH IS '하위레벨코드길이';
COMMENT ON COLUMN COMCODE.CMT IS '비고';

CREATE TABLE COMFILEINFO (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	FILE_ID					BINARY(16)	 	NOT NULL 	,
	UUID				  	VARCHAR2(1000)	NOT NULL 	,
	FILE_NM				  	VARCHAR2(1000)	NULL 		,
	FILE_SIZE			  	NUMBER			NULL 		,
	FILE_PATH			  	VARCHAR2(1000)	NULL 		,		
	APP_URL				  	VARCHAR2(50)	NULL 		,
	USER_ID				  	VARCHAR2(20)	NULL		,
	CONTENT_TYPE		  	VARCHAR2(50)	NULL 		,		
	DOWNLOAD_CNT		  	NUMBER			NULL 		,
	constraint pk_comfileinfo primary key(FILE_ID)
); 

COMMENT ON TABLE COMFILEINFO  IS '공통파일정보';
COMMENT ON COLUMN COMFILEINFO.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN COMFILEINFO.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN COMFILEINFO.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN COMFILEINFO.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN COMFILEINFO.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN COMFILEINFO.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN COMFILEINFO.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN COMFILEINFO.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN COMFILEINFO.FILE_ID		 	IS '파일ID';
COMMENT ON COLUMN COMFILEINFO.UUID				IS 'UUID_서버에저장된파일명';
COMMENT ON COLUMN COMFILEINFO.FILE_NM			IS '파일명';
COMMENT ON COLUMN COMFILEINFO.FILE_SIZE			IS '파일사이즈';
COMMENT ON COLUMN COMFILEINFO.FILE_PATH			IS '파일경로';
COMMENT ON COLUMN COMFILEINFO.APP_URL		 	IS 'APPURL';
COMMENT ON COLUMN COMFILEINFO.USER_ID		 	IS '사용자ID';
COMMENT ON COLUMN COMFILEINFO.CONTENT_TYPE		IS 'CONTENT-TYPE';
COMMENT ON COLUMN COMFILEINFO.DOWNLOAD_CNT		IS '다운로드횟수';


CREATE TABLE COMDEPT (
	CREATED_DT			  	DATE				NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)	  	NULL		,
	MODIFIED_DT			  	DATE		    	NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	  	NULL		,
	DEPT_ID				    VARCHAR2(10) 	  	NOT NULL 	,
	ORG_CD				    VARCHAR2(50)		NULL		,
  	DEPT_CD				    VARCHAR2(10) 	  	NOT NULL 	,
  	P_DEPT_ID			    VARCHAR2(255)	  	NULL 		,
  	DEPT_NM_KOR			  	VARCHAR2(255) 	  	NOT NULL 	,
	DEPT_ABBR_KOR		  	VARCHAR2(255) 	  	NULL 		,
  	DEPT_NM_ENG			  	VARCHAR2(255) 	  	NULL 		,
	DEPT_ABBR_ENG		  	VARCHAR2(255) 	  	NULL 		,
	FROM_DT				    DATE			  	NULL		,
	TO_DT				    DATE			  	NULL		,	
	PRT_SEQ				    INT					NULL		,		
	CMT					    VARCHAR2(2000) 		NULL 		,
	constraint pk_comdept 		primary key(DEPT_ID),
	constraint fk_comdept1	 	foreign key(P_DEPT_ID) references COMDEPT(DEPT_ID)
); 

COMMENT ON TABLE COMCODE IS '부서정보';
COMMENT ON COLUMN COMCODE.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN COMCODE.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN COMCODE.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN COMCODE.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN COMCODE.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN COMCODE.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN COMCODE.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN COMCODE.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN COMCODE.DEPT_ID 			IS '부서ID';
COMMENT ON COLUMN COMCODE.ORG_CD 			IS '회사코드';
COMMENT ON COLUMN COMCODE.DEPT_CD 			IS '부서코드';
COMMENT ON COLUMN COMCODE.P_DEPT_ID 		IS '상위부서ID';
COMMENT ON COLUMN COMCODE.DEPT_NM_KOR 		IS '부서명(한글)';
COMMENT ON COLUMN COMCODE.DEPT_ABBR_KOR 	IS '부서약어(한글)';
COMMENT ON COLUMN COMCODE.DEPT_NM_ENG 		IS '부서명(영어)';
COMMENT ON COLUMN COMCODE.DEPT_ABBR_ENG 	IS '부서약어(영어)';
COMMENT ON COLUMN COMCODE.FROM_DT 			IS '시작일';
COMMENT ON COLUMN COMCODE.TO_DT 			IS '종료일';
COMMENT ON COLUMN COMCODE.PRT_SEQ 			IS '출력순서';
COMMENT ON COLUMN COMCODE.CMT	 			IS '비고';


CREATE TABLE COMMENUGROUP (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT			  	DATE				NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,	
	ORG_CD				    VARCHAR2(10)		NULL		,
	MENU_GROUP_CD			VARCHAR2(10)		NOT NULL	,
  	MENU_GROUP_NM			VARCHAR2(50)		NOT NULL	,
	MENU_GROUP_URL		  	VARCHAR2(50)		NOT NULL	,
  	DESCRIPTION			  	VARCHAR2(500)		NULL		,
	constraint pk_commenugroup	primary key(ORG_CD, MENU_GROUP_CD)
);
COMMENT ON TABLE COMMENUGROUP IS '메뉴그룹정보';
COMMENT ON COLUMN COMMENUGROUP.CREATED_DT 			IS '최초등록일시';
COMMENT ON COLUMN COMMENUGROUP.CREATED_USER_ID 		IS '최초등록유저';
COMMENT ON COLUMN COMMENUGROUP.CREATED_HOST_IP 		IS '최초등록IP';
COMMENT ON COLUMN COMMENUGROUP.CREATED_APP_URL 		IS '최초등록APPURL';
COMMENT ON COLUMN COMMENUGROUP.MODIFIED_DT 			IS '최종수정일시';
COMMENT ON COLUMN COMMENUGROUP.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN COMMENUGROUP.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN COMMENUGROUP.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN COMMENUGROUP.ORG_CD 				IS '회사코드';
COMMENT ON COLUMN COMMENUGROUP.MENU_GROUP_CD 		IS '메뉴그룹코드';
COMMENT ON COLUMN COMMENUGROUP.MENU_GROUP_NM 		IS '메뉴그룹명';
COMMENT ON COLUMN COMMENUGROUP.MENU_GROUP_URL 		IS '메뉴그룹URL';
COMMENT ON COLUMN COMMENUGROUP.DESCRIPTION 			IS '비고';


CREATE TABLE COMMENU (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT				DATE				NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,	
	ORG_CD				    VARCHAR2(10)		NOT NULL	,
	MENU_GROUP_CD		  	VARCHAR2(50)		NOT NULL	,
	MENU_CD			        VARCHAR2(10)		NOT NULL	,
	MENU_NM			        VARCHAR2(50)		NOT NULL	,
	MENU_TYPE			    VARCHAR2(10)		NOT NULL	,
	P_MENU_CD			    VARCHAR2(50)		NULL		,	
	APP_URL				    VARCHAR2(50)		NULL		,
	SEQ					    NUMBER				NULL		,
	LVL					    NUMBER				NULL		,
	constraint pk_commenu		primary key(ORG_CD, MENU_GROUP_CD, MENU_CD)
);
COMMENT ON TABLE COMMENU IS '메뉴정보';
COMMENT ON COLUMN COMMENU.CREATED_DT 			IS '최초등록일시';
COMMENT ON COLUMN COMMENU.CREATED_USER_ID 		IS '최초등록유저';
COMMENT ON COLUMN COMMENU.CREATED_HOST_IP 		IS '최초등록IP';
COMMENT ON COLUMN COMMENU.CREATED_APP_URL 		IS '최초등록APPURL';
COMMENT ON COLUMN COMMENU.MODIFIED_DT 			IS '최종수정일시';
COMMENT ON COLUMN COMMENU.MODIFIED_USER_ID 		IS '최종수정유저';
COMMENT ON COLUMN COMMENU.MODIFIED_HOST_IP 		IS '최종수정IP';
COMMENT ON COLUMN COMMENU.MODIFIED_APP_URL 		IS '최종수정APPURL';
COMMENT ON COLUMN COMMENU.ORG_CD 				IS '회사코드';
COMMENT ON COLUMN COMMENU.MENU_GROUP_CD 		IS '메뉴그룹코드';
COMMENT ON COLUMN COMMENU.MENU_GROUP_NM 		IS '메뉴그룹명';
COMMENT ON COLUMN COMMENU.MENU_GROUP_URL 		IS '메뉴그룹URL';
COMMENT ON COLUMN COMMENU.DESCRIPTION 			IS '비고';


CREATE TABLE COMROLE (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT			  	DATE				NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,	
	ORG_CD				    VARCHAR2(50)		NOT NULL	,
	ROLE_CD				    VARCHAR2(50)		NOT NULL	,
  	ROLE_NM             	VARCHAR2(50)		NULL    	,
  	MENU_GROUP_CD			VARCHAR2(10)		NULL    	,
  	DESCRIPTION			  	VARCHAR2(500)		NULL		,
	constraint pk_comrole primary key(ORG_CD, ROLE_CD)
);

COMMENT ON TABLE COMROLE IS '롤정보';
COMMENT ON COLUMN COMROLE.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN COMROLE.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN COMROLE.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN COMROLE.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN COMROLE.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN COMROLE.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN COMROLE.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN COMROLE.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN COMROLE.ORG_CD		 	IS '회사코드';
COMMENT ON COLUMN COMROLE.ROLE_CD		 	IS '롤코드';
COMMENT ON COLUMN COMROLE.ROLE_NM		 	IS '롤명';
COMMENT ON COLUMN COMROLE.MENU_GROUP_CD	 	IS '메뉴그룹코드';
COMMENT ON COLUMN COMROLE.DESCRIPTION	 	IS '비고';


CREATE TABLE COMUSERROLE (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT			  	DATE				NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,
  	ORG_CD				    VARCHAR2(50)		NOT NULL	,
  	USER_ID				    VARCHAR2(50)		NOT NULL	,
	ROLE_CD				    VARCHAR2(50)		NOT NULL	,
	constraint pk_comuserrole 	primary key(ORG_CD, USER_ID, ROLE_CD)
	/*constraint fk_comuserauthority1	foreign key(USER_ID) references COMUSER(USER_ID)*/
	/*constraint fk_comuserauthority2	foreign key(AUTH_CD) references COMAUTHORITY(AUTH_CD)*/
); 
COMMENT ON TABLE COMUSERROLE IS '사용자롤매핑정보';
COMMENT ON COLUMN COMUSERROLE.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN COMUSERROLE.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN COMUSERROLE.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN COMUSERROLE.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN COMUSERROLE.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN COMUSERROLE.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN COMUSERROLE.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN COMUSERROLE.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN COMUSERROLE.ORG_CD		 	IS '회사코드';
COMMENT ON COLUMN COMUSERROLE.USER_ID		 	IS '사용자ID';
COMMENT ON COLUMN COMUSERROLE.ROLE_CD		 	IS '롤코드';

CREATE TABLE COMMENUROLE (
	CREATED_DT			  	DATE		  		NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT				DATE				NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,	
	ORG_CD				    VARCHAR2(10)		NOT NULL	,
	MENU_GROUP_CD		  	VARCHAR2(50)		NOT NULL	,
  	MENU_CD			        VARCHAR2(10)		NOT NULL	,
	ROLE_CD				    VARCHAR2(50)		NOT NULL	,
	constraint pk_commenurole		primary key(ORG_CD, MENU_GROUP_CD, MENU_CD, ROLE_CD)
);
COMMENT ON TABLE COMMENUROLE IS '메뉴롤관계정보';
COMMENT ON COLUMN COMMENUROLE.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN COMMENUROLE.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN COMMENUROLE.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN COMMENUROLE.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN COMMENUROLE.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN COMMENUROLE.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN COMMENUROLE.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN COMMENUROLE.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN COMMENUROLE.ORG_CD		 	IS '회사코드';
COMMENT ON COLUMN COMMENUROLE.MENU_GROUP_CD		IS '메뉴그룹코드';
COMMENT ON COLUMN COMMENUROLE.MENU_CD		 	IS '메뉴코드';
COMMENT ON COLUMN COMMENUROLE.ROLE_CD		 	IS '롤코드';


CREATE TABLE COMRESOURCE (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT			  	DATE			  	NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,
  	RESOURCE_ID	  	  		VARCHAR2(10)		NOT NULL	,
  	RESOURCE_NAME		  	VARCHAR2(50)		NOT NULL	,
  	RESOURCE_TYPE		  	VARCHAR2(10)		NOT NULL	,
  	URL					    VARCHAR2(500)		NULL		,
  	DESCRIPTION			  	VARCHAR2(500)		NULL		,
	constraint pk_comresource	primary key(RESOURCE_ID)
);
COMMENT ON TABLE COMRESOURCE IS '웹서버리소스정보';
COMMENT ON COLUMN COMRESOURCE.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN COMRESOURCE.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN COMRESOURCE.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN COMRESOURCE.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN COMRESOURCE.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN COMRESOURCE.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN COMRESOURCE.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN COMRESOURCE.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN COMMENUROLE.RESOURCE_ID		IS '리소스ID';
COMMENT ON COLUMN COMMENUROLE.RESOURCE_NAME		IS '리소스명';
COMMENT ON COLUMN COMMENUROLE.RESOURCE_TYPE		IS '리소스구분';
COMMENT ON COLUMN COMMENUROLE.URL				IS 'URL';
COMMENT ON COLUMN COMMENUROLE.DESCRIPTION		IS '비고';

CREATE TABLE COMHOLIDAY (
	CREATED_DT			  	DATE			    NULL		,
	CREATED_USER_ID			VARCHAR2(50)	  	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	  	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	  	NULL		,
	MODIFIED_DT			  	DATE			    NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	  	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	  	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	  	NULL		,
	ORG_CD				    VARCHAR2(10)		NOT NULL	,
  	HOLIDAY_DT			  	DATE			  	NOT NULL	,
	HOLIDAY_NM			  	VARCHAR2(255)  		NOT NULL 	,
	CMT					    VARCHAR2(2000) 		NULL 		,
	constraint pk_comholiday primary key(ORG_CD, HOLIDAY_DT)	
);
COMMENT ON TABLE COMHOLIDAY IS '공휴일정보';
COMMENT ON COLUMN COMHOLIDAY.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN COMHOLIDAY.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN COMHOLIDAY.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN COMHOLIDAY.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN COMHOLIDAY.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN COMHOLIDAY.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN COMHOLIDAY.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN COMHOLIDAY.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN COMHOLIDAY.ORG_CD 			IS '회사코드';
COMMENT ON COLUMN COMHOLIDAY.HOLIDAY_DT			IS '휴일';
COMMENT ON COLUMN COMHOLIDAY.HOLIDAY_NM			IS '휴일명';
COMMENT ON COLUMN COMHOLIDAY.CMT				IS '비고';

CREATE TABLE BIZCODETYPE (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT			  	DATE				NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,
  	ORG_CD				   	VARCHAR2(10)		NOT NULL	,
	TYPE_ID				   	VARCHAR2(10)		NOT NULL	,
	TYPE_NM				   	VARCHAR2(500)		NOT NULL	,
	PRT_SEQ			      	NUMBER	       		NULL		,
  	BIZ_TYPE				VARCHAR2(10)	  	NULL    	,
  	BIZ_RULE_CMT_1      	VARCHAR2(500)	  	NULL    	,
  	BIZ_RULE_CMT_2      	VARCHAR2(500)	  	NULL    	,
  	BIZ_RULE_CMT_3      	VARCHAR2(500)	  	NULL    	,
  	BIZ_RULE_CMT_4      	VARCHAR2(500)	  	NULL    	,
  	BIZ_RULE_CMT_5      	VARCHAR2(500)	  	NULL    	,
	BIZ_RULE_CMT_6      	VARCHAR2(500)	  	NULL    	,
  	BIZ_RULE_CMT_7      	VARCHAR2(500)	  	NULL    	,
  	BIZ_RULE_CMT_8      	VARCHAR2(500)	  	NULL    	,
  	BIZ_RULE_CMT_9      	VARCHAR2(500)	  	NULL    	,
  	BIZ_RULE_CMT_10     	VARCHAR2(500)	  	NULL    	,
	CMT					    VARCHAR2(4000)		NULL 		,
	constraint pk_bizcodetype primary key(ORG_CD, TYPE_ID)
);
COMMENT ON TABLE BIZCODETYPE IS '업무코드구분정보';
COMMENT ON COLUMN BIZCODETYPE.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN BIZCODETYPE.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN BIZCODETYPE.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN BIZCODETYPE.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN BIZCODETYPE.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN BIZCODETYPE.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN BIZCODETYPE.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN BIZCODETYPE.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN BIZCODETYPE.ORG_CD 			IS '회사코드';
COMMENT ON COLUMN BIZCODETYPE.TYPE_ID 			IS '구분ID';
COMMENT ON COLUMN BIZCODETYPE.TYPE_NM 			IS '구분명';
COMMENT ON COLUMN BIZCODETYPE.PRT_SEQ 			IS '출력순서';
COMMENT ON COLUMN BIZCODETYPE.BIZ_TYPE 			IS '업무구분';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_1 	IS '업무규칙비고1';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_2 	IS '업무규칙비고2';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_3 	IS '업무규칙비고3';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_4 	IS '업무규칙비고4';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_5 	IS '업무규칙비고5';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_6 	IS '업무규칙비고6';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_7 	IS '업무규칙비고7';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_8 	IS '업무규칙비고8';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_9 	IS '업무규칙비고9';
COMMENT ON COLUMN BIZCODETYPE.BIZ_RULE_CMT_10 	IS '업무규칙비고10';
COMMENT ON COLUMN BIZCODETYPE.CMT 				IS '비고';


CREATE TABLE BIZCODE (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT			  	DATE				NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,
  	ORG_CD				    VARCHAR2(10)		NOT NULL	,
	TYPE_ID				    VARCHAR2(10)		NOT NULL	,
  	CODE	  			    VARCHAR2(10)		NOT NULL	,  
	CODE_NM				    VARCHAR2(500)		NULL    	,
	USE_YN  				BOOLEAN	    	  	NULL    	,
	PRT_SEQ			      	NUMBER		    	NULL		,    
	CMT					    VARCHAR2(4000)		NULL 		,
	constraint pk_bizcode primary key(ORG_CD, TYPE_ID, CODE)
);
COMMENT ON TABLE BIZCODE IS '업무코드정보';
COMMENT ON COLUMN BIZCODE.CREATED_DT 		IS '최초등록일시';
COMMENT ON COLUMN BIZCODE.CREATED_USER_ID 	IS '최초등록유저';
COMMENT ON COLUMN BIZCODE.CREATED_HOST_IP 	IS '최초등록IP';
COMMENT ON COLUMN BIZCODE.CREATED_APP_URL 	IS '최초등록APPURL';
COMMENT ON COLUMN BIZCODE.MODIFIED_DT 		IS '최종수정일시';
COMMENT ON COLUMN BIZCODE.MODIFIED_USER_ID 	IS '최종수정유저';
COMMENT ON COLUMN BIZCODE.MODIFIED_HOST_IP 	IS '최종수정IP';
COMMENT ON COLUMN BIZCODE.MODIFIED_APP_URL 	IS '최종수정APPURL';
COMMENT ON COLUMN BIZCODE.ORG_CD 			IS '회사코드';
COMMENT ON COLUMN BIZCODE.TYPE_ID 			IS '구분ID';
COMMENT ON COLUMN BIZCODE.CODE	 			IS '코드';
COMMENT ON COLUMN BIZCODE.CODE_NM 			IS '코드명';
COMMENT ON COLUMN BIZCODE.USE_YN 			IS '사용여부';
COMMENT ON COLUMN BIZCODE.PRT_SEQ 			IS '출력순서';
COMMENT ON COLUMN BIZCODE.CMT	 			IS '비고';


CREATE TABLE COMTERMDOMAIN (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT			  	DATE			  	NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,
	DOMAIN_ID			    VARCHAR2(600)		NOT NULL	,
	DB					    VARCHAR2(600)		NOT NULL	,
	DOMAIN_NAME			  	VARCHAR2(600)		NOT NULL	,
	DATA_TYPE			    VARCHAR2(600)		NOT NULL	,
	CMT					    VARCHAR2(4000)	    NULL 		,
	constraint pk_comtermdomain primary key(DOMAIN_ID)	
);
COMMENT ON TABLE COMTERMDOMAIN IS '데이터도메인';

CREATE TABLE COMTERMWORD (
	CREATED_DT				DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT				DATE			  	NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,
	LOGICAL_NAME		  	VARCHAR2(600)		NOT NULL	,
	LOGICAL_NAME_ENG		VARCHAR2(600)		NULL		,
	PHYSICAL_NAME			VARCHAR2(600)		NOT NULL	,
	CMT					    VARCHAR2(4000)	    NULL 		,
	constraint pk_comtermword primary key(LOGICAL_NAME)	
);
COMMENT ON TABLE COMTERMWORD IS '단어사전';


CREATE TABLE COMTERM (
	CREATED_DT			  	DATE			  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)		NULL		,
	MODIFIED_DT			  	DATE			  	NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)		NULL		,
	TERM_ID				    VARCHAR2(600)		NOT NULL	,
	SYSTEM				    VARCHAR2(600)		NOT NULL	,
	TERM				    VARCHAR2(600)		NOT NULL	,
	TERM_ENG			    VARCHAR2(600)		NULL		,
	COLUMN_NAME			  	VARCHAR2(600)		NULL		,
	DOMAIN_ID			    VARCHAR2(600)		NOT NULL	,
	COMBI_YN			    BOOLEAN				NOT NULL	,
	TERM_DESCRIPTION		VARCHAR2(4000)      NULL 		,
	CMT					   	VARCHAR2(4000)	    NULL 		,
	constraint pk_comterm primary key(TERM_ID),
	constraint fk_comterm1 	foreign key(DOMAIN_ID) references COMTERMDOMAIN(DOMAIN_ID)
); 
COMMENT ON TABLE COMTERM IS '용어사전';
